
import { StyleSheet } from "react-native";
import { responsiveWidth, responsiveHeight } from 'react-native-responsive-dimensions'; // Add missing imports

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  header: {
    backgroundColor: '#065E2C',
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    paddingHorizontal: responsiveWidth(5),
    paddingTop: responsiveHeight(6),
    paddingBottom: responsiveHeight(2),
  },
  backButton: {
    width: responsiveWidth(7),
  },
  headerTitle: {
    color: '#fff',
    fontSize: 20,
    fontWeight: '700',
  },
  profileButton: {
    width: responsiveWidth(7),
  },
  savingsText: {
    color: '#065E2C',
    fontWeight: '600',
    fontSize: 14,
  },
  content: {
    flex: 1,
    // padding: responsiveWidth(5),
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000',
    // marginBottom: responsiveHeight(2),
    marginLeft: responsiveWidth(5),
    marginVertical: responsiveHeight(2),
  },
  cartItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
  },
  foodImage: {
    width: 82,
    height: 82,
    borderRadius: 12,
  },
  itemDetails: {
    flex: 1,
    marginLeft: 16,
    gap: 3,
    justifyContent: 'center',
  },
  foodName: {
    fontSize: 16,
    color: '#000',
    fontWeight: '500',
    width: '60%',
  },
  foodPrice: {
    fontSize: 16,
    color: '#065E2C',
    fontWeight: '700',
  },
  quantityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#065E2C',
    borderRadius: 6,
  },
  quantityButton: {
    padding: 5,
  },
  quantityText: {
    fontSize: 14,
    fontWeight: '600',
    marginHorizontal: 5,
    color: '#065E2C',
  },
  itemTotalPrice: {
    color: '#3D3D3D',
    fontSize: 14,
    fontWeight: '800',
    textAlign: 'right',
    marginTop: 3,
  },
  addMoreButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: responsiveHeight(3),
  },
  addMoreText: {
    color: '#C3A710',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'left',
  },
  detailsCard: {
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 15,
    marginBottom: responsiveHeight(2),
    // shadowColor: '#000',
    // shadowOffset: {
    //   width: 0,
    //   height: 2,
    // },
    // shadowOpacity: 0.1,
    // shadowRadius: 4,
    // elevation: 3,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '500',
    color: '#666',
    marginLeft: responsiveWidth(2),
    marginBottom: 5,
  },
  addressSection: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 15,
    gap: 10,
    // padding: 10,
    // paddingVertical: 15,
  },
  addressDetails: {
    flex: 1,
  },
  addressType: {
    fontSize: 14,
    fontWeight: '600',
    color: '#000',
    marginBottom: 4,
  },
  addressText: {
    fontSize: 14,
    color: '#3D3D3D',
    lineHeight: 18,
    fontWeight: '400',
  },
  contactSection: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  contactDetails: {
    flex: 1,
  },
  contactName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#000',
  },
  contactNumber: {
    fontSize: 12,
    color: '#666',
  },
  couponCard: {
    width: responsiveWidth(90),
    alignSelf: 'center',
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 15,
    marginBottom: responsiveHeight(2),
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: '#065E2C',
    // shadowColor: '#000',
    // shadowOffset: {
    //   width: 0,
    //   height: 2,
    // },
    // shadowOpacity: 0.1,
    // shadowRadius: 4,
    // elevation: 3,
  },
  couponText: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    color: '#000',
  },
  billingCard: {
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 15,
    marginBottom: responsiveHeight(2),
    borderWidth: 1,
    width: responsiveWidth(90),
    alignSelf: 'center',
    borderColor: '#065E2C',
    // shadowColor: '#000',
    // shadowOffset: {
    //   width: 0,
    //   height: 2,
    // },
    // shadowOpacity: 0.1,
    // shadowRadius: 4,
    // elevation: 3,
  },
  billRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  billLabel: {
    fontSize: 16,
    color: '#525252',
    fontWeight: '500',
  },
  billValue: {
    fontSize: 15,
    color: '#000',
    fontWeight: '500',
  },
  savingsValue: {
    fontSize: 15,
    color: '#525252',
    fontWeight: '500',
  },
  gstValue: {
    fontSize: 15,
    color: '#FFCB18',
    fontWeight: '500',
  },
  couponCode: {
    fontSize: 12,
    color: '#065E2C',
    fontWeight: '500',
    marginLeft: 10,
    marginBottom: 10,
  },
  gstNote: {
    fontSize: 12,
    color: '#666',
    marginLeft: 0,
    marginBottom: 15,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    // borderTopWidth: 1,
    // borderTopColor: '#E0E0E0',
    paddingTop: 15,
  },
  totalLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000',
  },
  totalValue: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000',
  },
  paymentSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 15,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
  },
  paymentMethod: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    backgroundColor: '#f0f0f0',
    borderRadius: 8,
  },
  paymentMethodText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000',
  },
  placeOrderButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#065E2C',
    borderRadius: 8,
    padding: 15,
    marginLeft: 10,
  },
  placeOrderContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flex: 1,
  },
  orderTotal: {
    alignItems: 'flex-start',
  },
  orderTotalValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
  },
  orderTotalLabel: {
    fontSize: 14,
    color: '#fff',
  },
  placeOrderTextContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  placeOrderText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#fff',
    marginRight: 5,
  },
  totalContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: responsiveWidth(5),
    marginTop: responsiveHeight(2),
  },
  totalPrice: {
    fontSize: 18,
    color: '#065E2C',
    fontWeight: '700',
  },
  dottedLineContainer: {
    flexDirection: 'row',
    marginTop: 5,
    alignSelf: 'center',
  },
  dot: {
    width: 7, // Dot size
    height: 2,
    backgroundColor: '#D8D8D8', // Dot color
    borderRadius: 5, // Makes it circular
    marginHorizontal: 5, // Space between dots
  },
  savingsBanner: {
    width: responsiveWidth(90),
    alignSelf: 'center',
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: responsiveHeight(1.5),
    borderWidth: 1,
    borderColor: '#065E2C',
    borderRadius: 8,
    gap: 8,
    marginVertical: responsiveHeight(2),
  },
  headerTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  supportButton: {
    width: 44,
    height: 44,
    backgroundColor: '#fff',
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  appliedCouponContainer: {
    backgroundColor: '#fff',
    padding: 15,
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  appliedCouponText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000',
  },
  removeCouponText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#065E2C',
  },
  paymentMethodsContainer: {
    position: 'absolute',
    top: -responsiveHeight(10), // Adjust based on your layout
    left: 10,
    // right: 0,
    backgroundColor: '#fff',
    borderRadius: 8,
    elevation: 5,
    padding: 10,
    zIndex: 1, 
  },
  paymentMethodItem: {
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)', // Semi-transparent background
  },
  modalContent: {
    width: '80%',
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 20,
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  modalMessage: {
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 20,
  },
  modalButton: {
    backgroundColor: '#065E2C',
    borderRadius: 5,
    padding: 10,
    width: '100%',
    alignItems: 'center',
  },
  modalButtonText: {
    color: 'white',
    fontSize: 16,
  },
  totalText: {
    fontSize: 16,
    color: '#000',
  },
  amountText: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  address: {
    marginHorizontal: responsiveWidth(1),
    borderWidth: 1,
    borderColor: '#065E2C',
    borderRadius: 8,
  },
  address:{
    padding: 15,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#065E2C',
  },
});