export const baseURL = 'https://intlokitchen.com:2030/public_app/'; 

export const endpoints = {
  VERIFY_MOBILE:'customers/v1/loginCheck',
  LOGIN:'customers/v1/otpAuth',
  SIGNUP: 'customers/v1/loginCheck',
  TOUR_PACKAGES:'packages/v1/getAll',
  GET_RENTAL_ITEMS:"rentalItems/v1/getAll",
  GET_ALL_ORDERS:'categories/v1/getAll',
  DADDY_GET_CATEGORIES:'getcategory',
  GET_CATEGORY_ITEMS:'getitems',
  GET_SUB_CATEGORIES:'public_app/getshopsubcategorylist',
  GET_BANNER:'getbanners',
  GET_SHOPS:'public_app/getshoplist',
  GET_ITEMS_LIST:"public_app/getitemslist",
  VERIFY_CUSTOMER_MOBILE:'public_app/customerlogin',
  VERIFY_CUSTOMER_OTP:'customerlogin',
  GET_ORDERS:'getorderlist',
  GET_ALL_CATEGORIES:'public_app/getsubcategoryall',
  GET_ADDRESS_LIST:'getdeliveryaddress',
  SET_ADDRESS_LIST:'adddeliveryaddress',
  DELETE_ADDRESS_LIST:'deletedeliveryaddress',
  GET_ORDER_DETAILS:'getorderdetails',
  CHECK_ADDRESS_EXISTENCE:'public_app/getuserlocation',
  GET_SERVICES_LIST:'public_app/getserviceslist',
  GET_COUPONS:'getcoupon',
  PLACE_ORDER:'orderplaced',
  GET_CHARGES_LIST:'getapplicationdata',
  REQUEST_OTP:'getuserloginotp',
  GLOBAL_SEARCH:'public_app/search_allitems',
  GIVE_APP_FEEDBACK:'public_app/postapprating',
  CANCEL_ORDER:'public_app/cancleorder',
  GIVE_ORDER_RATING:"public_app/postorderrating",
  GENERATE_ORDER_ID:'public_app/generateorderid',
  UPDATE_ORDER_STATUS:'public_app/updatepaymetdetails',
  GET_RESULT_FULL_DATA:'public_app/searchitemsfull',
  GET_NOTIFICATIONS:'public_app/notificationslist',
  DELETE_ACCOUNT:'public_app/deleteaccount',
  GET_SEARCH_SHOP_LIST:"public_app/getsearchshoplist",
  GET_SINGLE_SHOP_DETAILS:"public_app/getsingleshopdetails",
  GET_SEARCH_SUB_CATEGORIES:"public_app/getsearchsubcategoriesshoplist",
  GET_SEARCH_CATEGORIES:"public_app/getsearchcategoriesshoplist",

  GET_AVAILABLE_LOCATIONS:'getavailablelocations',
  GET_APPLICATION_DATA:'getapplicationdata'
};
